### PR TITLE
Let user choose between black/white or color output

### PR DESCRIPTION
**Pull request by deadda7a**
I only have access to a black and white card printer. Therefore I added a b/w template and an option to let the user specify if they want the colored or the b/w output. Defaults to color.

### CODE REVIEW

**Comment by lumbric** [comment]
Oh amazing, thanks for the pull request! If you want, you could include a test case in the poor-man-testcase framework: it simply executes the [script directly from the Github action](https://github.com/lumbric/green-pass-generator/blob/main/.github/workflows/tests.yml#L49) with different parameters. But I guess we can merge it also without tests. Note sure if I should hope that we will need the cards again or that we won't need them... :thinking: 

(Sorry for the late reply!)

**Comment by lumbric** [comment]
I think the layout could be changed a bit, since there is no white border any longer. But this might be a bit more work. The `qr_scaling_factor` may need some adaptions, but I am not sure.

**Comment by deadda7a** [comment]
I will add a test to the Github actions, tbh I missed they exist and therefore didn't adapt them :smiley_cat: 
To the template, I have like zero knowledge about how to create vector graphics in a sane way, the way I created the template is to open the svg in my text editor and edit it manually :sweat_smile:

**Comment by lumbric** [comment]
Ah ok :) The template is done in Inkscape, no rocket science, but I don't remember myself if there was some post processing necessary or not.

**Pull request merged**
